name: Continuous Integration - Automate Tests on Main Branch

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: run automated Python UnitTest tests on any Push to Main branch
        run: python "Prnc&Prdg-PrgLng_Asgn_Stack/test_main.py"

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies and build
        run: |
          NUnitassignment/NUnitassignment.sln
          dotnet restore
          dotnet build

      - name: run automated C# NUnit tests on any Push to Main branch
        run: dotnet test NUnitassignment/NUnitassignment/NUnitassignment.csproj
